server:
  port: 8091
  servlet:
    # 解决使用flux流式返回乱码
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: embed2Vector
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: glm-5.2
      # 向量模型
      embedding:
        options:
          model: text-embedding-v3
    # redis vectorstore
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index-
        prefix: custom-prefix-
  data:
    redis:
      host: localhost
      port: 16379
      password: root
