server:
  port: 8087
  servlet:
    # 解决使用flux流式返回乱码
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: structuredOutput
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
