server.port=8016

# 设置全局编码格式
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=15-clientCallBaiduMcpServer

# ==== Spring AI Alibaba Config =============
spring.ai.dashscope.api-key=${AI_DASHSCOPE_API_KEY}

# ==== mcp-client Config=============
spring.ai.mcp.client.request-timeout=20s
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.stdio.servers-configuration=classpath:/mcp-server.json5
