
spring:
  main:
    web-application-type: none
    banner-mode: off
  application:
    name: my-mcp-server-stdio
  ai:
    mcp:
      server:
        enabled: true
        version: 1.0.0
        name: my-weather-mcp-server-stdio
        stdio: true


